/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package upt.qs.ficha4gradle;

public class Library {
	
    public boolean someLibraryMethod() {
        return true;
    }
    
}
